apiVersion: v1
kind: Service
metadata:
  name: reactapp-service
  namespace: ngin
spec:
  type: NodePort
  selector:
    app: reactapp
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30505