apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-deployment
  namespace: ngin
  labels:
    app: reactapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
      - name: reactapp
        imagePullPolicy: Always
        image: eastyler/nginsample:works 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reactapp-service
  namespace: ngin
spec:
  type: NodePort
  selector:
    app: reactapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30505
